/**
 * Client-side ZIP bundle for agent plan downloads.
 *
 * Creates a ZIP containing AGENTS.md, CLAUDE.md, and a README with
 * usage instructions for various AI coding assistants.
 */

import { zipSync, strToU8 } from "fflate";

// ═══════════════════════════════════════════════════════════════════════════
// Types
// ═══════════════════════════════════════════════════════════════════════════

interface CreateZipInput {
  agentPlanMd: string;
  siteDomain: string;
}

// ═══════════════════════════════════════════════════════════════════════════
// Constants
// ═══════════════════════════════════════════════════════════════════════════

const CLAUDE_MD = `# CLAUDE.md

Strictly follow the rules in ./AGENTS.md
`;

const README_MD = `# Agent Fix Plan — Generated by A11y Garden

This folder contains an AI-generated fix plan for accessibility violations
detected by [A11y Garden](https://a11ygarden.org).

## How to Use

### Cursor
1. Copy the included \`AGENTS.md\` into your project root.
2. Open your project in Cursor, switch to Agent mode, and prompt:
   \`Follow the fix plan in AGENTS.md\`

### Claude Code
1. Copy the included \`CLAUDE.md\` into \`.claude/CLAUDE.md\` in your project root (create the folder if needed). It references \`AGENTS.md\`, so copy that to your project root too.
2. Run \`claude\` from your project directory and prompt:
   \`Follow the fix plan in CLAUDE.md\`

### Codex
1. Copy the included \`AGENTS.md\` into your project root.
2. Open your project in Codex and prompt:
   \`Follow the fix plan in AGENTS.md\`

### GitHub Copilot
1. Copy the contents of \`AGENTS.md\` into \`.github/copilot-instructions.md\` in your repository.
2. Prompt Copilot: \`Follow the fix plan in copilot-instructions.md\`

## Re-run the Audit
Visit [a11ygarden.org](https://a11ygarden.org) to scan your site again
after applying the fixes.
`;

// ═══════════════════════════════════════════════════════════════════════════
// Utilities
// ═══════════════════════════════════════════════════════════════════════════

export function sanitizeDomain(domain: string): string {
  return domain
    .replace(/[^a-zA-Z0-9-]/g, "-")
    .replace(/-{2,}/g, "-")
    .replace(/^-+|-+$/g, "");
}

// ═══════════════════════════════════════════════════════════════════════════
// ZIP creation (returns Blob — no browser download side-effect)
// ═══════════════════════════════════════════════════════════════════════════

export function createAgentPlanZipBlob(input: CreateZipInput): Blob {
  const zipped = zipSync({
    "AGENTS.md": strToU8(input.agentPlanMd),
    "CLAUDE.md": strToU8(CLAUDE_MD),
    "README-agent-plan.md": strToU8(README_MD),
  });

  return new Blob([zipped.buffer as ArrayBuffer], { type: "application/zip" });
}

// ═══════════════════════════════════════════════════════════════════════════
// Browser download trigger
// ═══════════════════════════════════════════════════════════════════════════

export function downloadAgentPlanZip(input: CreateZipInput): void {
  const blob = createAgentPlanZipBlob(input);
  const safeDomain = sanitizeDomain(input.siteDomain);
  const filename = `a11y-fix-plan-${safeDomain}.zip`;

  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
