import { describe, it, expect } from "vitest";
import { generateMarkdownReport, type ReportData } from "./report";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Minimal valid report data for testing. Override fields as needed. */
function makeReport(overrides: Partial<ReportData> = {}): ReportData {
  return {
    url: "https://example.com",
    letterGrade: "B",
    score: 85,
    scannedAt: new Date("2026-01-15T12:00:00Z").getTime(),
    violations: {
      critical: 0,
      serious: 1,
      moderate: 3,
      minor: 2,
      total: 6,
    },
    ...overrides,
  };
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe("generateMarkdownReport", () => {
  // ═══════════════════════════════════════════════════════════════════════════
  // BASIC STRUCTURE
  // ═══════════════════════════════════════════════════════════════════════════

  describe("basic structure", () => {
    it("includes the report title", () => {
      const md = generateMarkdownReport(makeReport());

      expect(md).toContain("# Accessibility Report");
    });

    it("uses page title in heading when provided", () => {
      const md = generateMarkdownReport(
        makeReport({ pageTitle: "Walmart" }),
      );

      expect(md).toContain("# Walmart — Accessibility Report");
    });

    it("falls back to generic title when no page title", () => {
      const md = generateMarkdownReport(
        makeReport({ pageTitle: undefined }),
      );

      expect(md).toContain("# Accessibility Report");
      expect(md).not.toContain("undefined");
    });

    it("includes the URL", () => {
      const md = generateMarkdownReport(
        makeReport({ url: "https://walmart.com" }),
      );

      expect(md).toContain("**URL:** https://walmart.com");
    });

    it("includes the grade and score", () => {
      const md = generateMarkdownReport(
        makeReport({ letterGrade: "A", score: 95 }),
      );

      expect(md).toContain("**Grade:** A (95/100)");
    });

    it("includes the scan date", () => {
      const md = generateMarkdownReport(makeReport());

      // The date format is locale-dependent, but should contain the year
      expect(md).toContain("**Scanned:**");
      expect(md).toContain("2026");
    });

    it("includes the automated-checks disclaimer", () => {
      const md = generateMarkdownReport(makeReport());

      expect(md).toContain(
        "not a substitute for a comprehensive WCAG audit",
      );
    });

    it("includes the footer", () => {
      const md = generateMarkdownReport(makeReport());

      expect(md).toContain("Report generated by A11y Garden");
    });
  });

  // ═══════════════════════════════════════════════════════════════════════════
  // VIOLATIONS SUMMARY TABLE
  // ═══════════════════════════════════════════════════════════════════════════

  describe("violations summary table", () => {
    it("includes all severity counts", () => {
      const md = generateMarkdownReport(
        makeReport({
          violations: {
            critical: 2,
            serious: 4,
            moderate: 6,
            minor: 8,
            total: 20,
          },
        }),
      );

      expect(md).toContain("| Critical | 2 |");
      expect(md).toContain("| Serious | 4 |");
      expect(md).toContain("| Moderate | 6 |");
      expect(md).toContain("| Minor | 8 |");
      expect(md).toContain("| **Total** | **20** |");
    });

    it("shows zero counts correctly", () => {
      const md = generateMarkdownReport(
        makeReport({
          violations: {
            critical: 0,
            serious: 0,
            moderate: 0,
            minor: 0,
            total: 0,
          },
        }),
      );

      expect(md).toContain("| Critical | 0 |");
      expect(md).toContain("| **Total** | **0** |");
    });
  });

  // ═══════════════════════════════════════════════════════════════════════════
  // SAFE MODE
  // ═══════════════════════════════════════════════════════════════════════════

  describe("safe mode", () => {
    it("includes safe mode note when scanMode is 'safe'", () => {
      const md = generateMarkdownReport(
        makeReport({ scanMode: "safe" }),
      );

      expect(md).toContain("Safe Mode");
      expect(md).toContain("Not all checks were performed");
    });

    it("does not include safe mode note for full scans", () => {
      const md = generateMarkdownReport(
        makeReport({ scanMode: "full" }),
      );

      expect(md).not.toContain("Safe Mode");
    });

    it("does not include safe mode note when scanMode is undefined", () => {
      const md = generateMarkdownReport(
        makeReport({ scanMode: undefined }),
      );

      expect(md).not.toContain("Safe Mode");
    });
  });

  // ═══════════════════════════════════════════════════════════════════════════
  // REPORT URL
  // ═══════════════════════════════════════════════════════════════════════════

  describe("report URL", () => {
    it("includes full report link when reportUrl is provided", () => {
      const md = generateMarkdownReport(
        makeReport(),
        "https://a11y.garden/results/abc123",
      );

      expect(md).toContain(
        "**Full Report:** https://a11y.garden/results/abc123",
      );
    });

    it("does not include full report link when reportUrl is omitted", () => {
      const md = generateMarkdownReport(makeReport());

      expect(md).not.toContain("**Full Report:**");
    });
  });

  // ═══════════════════════════════════════════════════════════════════════════
  // AI SUMMARY
  // ═══════════════════════════════════════════════════════════════════════════

  describe("AI summary section", () => {
    it("includes AI summary when provided", () => {
      const md = generateMarkdownReport(
        makeReport({
          aiSummary:
            "This site has several accessibility issues affecting screen reader users.",
        }),
      );

      expect(md).toContain("## AI Summary");
      expect(md).toContain(
        "This site has several accessibility issues affecting screen reader users.",
      );
    });

    it("omits AI summary section when not provided", () => {
      const md = generateMarkdownReport(
        makeReport({ aiSummary: undefined }),
      );

      expect(md).not.toContain("## AI Summary");
    });

    it("omits AI summary section when empty string", () => {
      const md = generateMarkdownReport(makeReport({ aiSummary: "" }));

      expect(md).not.toContain("## AI Summary");
    });
  });

  // ═══════════════════════════════════════════════════════════════════════════
  // TOP ISSUES
  // ═══════════════════════════════════════════════════════════════════════════

  describe("top issues section", () => {
    it("includes numbered top issues when provided", () => {
      const md = generateMarkdownReport(
        makeReport({
          topIssues: [
            "Missing alt text on images",
            "Form inputs lack labels",
            "No skip navigation link",
          ],
        }),
      );

      expect(md).toContain("## Top Issues to Address");
      expect(md).toContain("1. Missing alt text on images");
      expect(md).toContain("2. Form inputs lack labels");
      expect(md).toContain("3. No skip navigation link");
    });

    it("omits top issues section when array is empty", () => {
      const md = generateMarkdownReport(makeReport({ topIssues: [] }));

      expect(md).not.toContain("## Top Issues to Address");
    });

    it("omits top issues section when not provided", () => {
      const md = generateMarkdownReport(
        makeReport({ topIssues: undefined }),
      );

      expect(md).not.toContain("## Top Issues to Address");
    });
  });

  // ═══════════════════════════════════════════════════════════════════════════
  // VIOLATIONS BY RULE
  // ═══════════════════════════════════════════════════════════════════════════

  describe("violations by rule section", () => {
    const sampleViolations = JSON.stringify([
      {
        id: "image-alt",
        impact: "critical",
        description: "Images must have alternate text",
        help: "Images must have alternate text",
        helpUrl: "https://dequeuniversity.com/rules/axe/4.10/image-alt",
        nodes: [{ html: "<img src='logo.png'>", target: ["img"] }],
      },
      {
        id: "link-name",
        impact: "serious",
        description: "Links must have discernible text",
        help: "Links must have discernible text",
        helpUrl: "https://dequeuniversity.com/rules/axe/4.10/link-name",
        nodes: [
          { html: "<a href='#'>", target: ["a"] },
          { html: "<a href='/about'>", target: ["a"] },
        ],
      },
      {
        id: "heading-order",
        impact: "moderate",
        description: "Heading levels should increase by one",
        help: "Heading levels should only increase by one",
        helpUrl:
          "https://dequeuniversity.com/rules/axe/4.10/heading-order",
        nodes: [{ html: "<h3>Title</h3>", target: ["h3"] }],
      },
    ]);

    it("groups violations by severity", () => {
      const md = generateMarkdownReport(
        makeReport({ rawViolations: sampleViolations }),
      );

      expect(md).toContain("## Violations by Rule");
      expect(md).toContain("### Critical");
      expect(md).toContain("### Serious");
      expect(md).toContain("### Moderate");
    });

    it("shows violation help text and rule ID", () => {
      const md = generateMarkdownReport(
        makeReport({ rawViolations: sampleViolations }),
      );

      expect(md).toContain(
        "**Images must have alternate text** (`image-alt`)",
      );
      expect(md).toContain(
        "**Links must have discernible text** (`link-name`)",
      );
    });

    it("shows element count (singular)", () => {
      const md = generateMarkdownReport(
        makeReport({ rawViolations: sampleViolations }),
      );

      expect(md).toContain("(`image-alt`) — 1 element\n");
    });

    it("shows element count (plural)", () => {
      const md = generateMarkdownReport(
        makeReport({ rawViolations: sampleViolations }),
      );

      expect(md).toContain("(`link-name`) — 2 elements\n");
    });

    it("omits violations section when rawViolations is undefined", () => {
      const md = generateMarkdownReport(
        makeReport({ rawViolations: undefined }),
      );

      expect(md).not.toContain("## Violations by Rule");
    });

    it("omits violations section when rawViolations is empty array", () => {
      const md = generateMarkdownReport(
        makeReport({ rawViolations: "[]" }),
      );

      expect(md).not.toContain("## Violations by Rule");
    });

    it("handles invalid JSON in rawViolations gracefully", () => {
      const md = generateMarkdownReport(
        makeReport({ rawViolations: "not valid json {{{" }),
      );

      // Should not throw, should not include the section
      expect(md).not.toContain("## Violations by Rule");
      expect(md).toContain("Report generated by A11y Garden");
    });

    it("skips severity groups with no violations", () => {
      const onlyModerate = JSON.stringify([
        {
          id: "heading-order",
          impact: "moderate",
          description: "test",
          help: "Heading order",
          helpUrl: "https://example.com",
          nodes: [{ html: "<h3>", target: ["h3"] }],
        },
      ]);

      const md = generateMarkdownReport(
        makeReport({ rawViolations: onlyModerate }),
      );

      expect(md).toContain("### Moderate");
      expect(md).not.toContain("### Critical");
      expect(md).not.toContain("### Serious");
      expect(md).not.toContain("### Minor");
    });
  });

  // ═══════════════════════════════════════════════════════════════════════════
  // COMPLETE REPORT
  // ═══════════════════════════════════════════════════════════════════════════

  describe("complete report with all sections", () => {
    it("includes all sections in correct order", () => {
      const md = generateMarkdownReport(
        makeReport({
          pageTitle: "Test Site",
          aiSummary: "AI generated summary here.",
          topIssues: ["Issue one", "Issue two"],
          rawViolations: JSON.stringify([
            {
              id: "image-alt",
              impact: "serious",
              description: "test",
              help: "Images need alt",
              helpUrl: "https://example.com",
              nodes: [{ html: "<img>", target: ["img"] }],
            },
          ]),
        }),
      );

      const titleIdx = md.indexOf("# Test Site");
      const summaryIdx = md.indexOf("## Violations Summary");
      const aiIdx = md.indexOf("## AI Summary");
      const issuesIdx = md.indexOf("## Top Issues");
      const rulesIdx = md.indexOf("## Violations by Rule");
      const footerIdx = md.indexOf("Report generated by A11y Garden");

      expect(titleIdx).toBeLessThan(summaryIdx);
      expect(summaryIdx).toBeLessThan(aiIdx);
      expect(aiIdx).toBeLessThan(issuesIdx);
      expect(issuesIdx).toBeLessThan(rulesIdx);
      expect(rulesIdx).toBeLessThan(footerIdx);
    });
  });
});
